sudo: true
language: rust
rust:
    - stable
    - beta
    - nightly

before_install:
  - curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
  - unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
  - sudo mv protoc3/bin/* /usr/local/bin/
  - sudo mv protoc3/include/* /usr/local/include/
  - curl -OL https://s3.amazonaws.com/snips/tensorflow-deb/libtensorflow_1.2.1-snips-1_amd64.deb
  - sudo dpkg -i libtensorflow_1.2.1-snips-1_amd64.deb

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --release --verbose --all

matrix:
  allow_failures:
    - rust: nightly

