language: rust
rust:
    - stable
    - beta
    - nightly

addons:
  apt:
    sources:
      - sourceline: ppa:maarten-fonville/protobuf
    packages:
      - protobuf

matrix:
  allow_failures:
    - rust: nightly

