sudo: true
language: rust
rust:
    - stable
    - beta
    - nightly

before_install:
  - sudo add-apt-repository ppa:maarten-fonville/protobuf -y
  - sudo apt-get update -q
  - sudo apt-get install protobuf -y

matrix:
  allow_failures:
    - rust: nightly

