[package]
name = "tfdeploy"
version = "0.0.3"
license = "MIT/Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow inference"
repository = "https://github.com/kali/tensorflow-deploy-rust"
keywords = [ "TensorFlow", "NeuralNetworks" ]
build="build.rs"
categories = [ "science" ]

[badges]
travis-ci = { repository = "kali/tensorflow-deploy-rust" }

[dependencies]
blas-sys = { version = "0.6", optional = true, default-features=false }
downcast-rs = "1.0"
error-chain =  { version = "0.10", default-features=false }
image = "0.15"
log = "0.3"
ndarray = { version = "0.10" }
num-traits = "0.1"
protobuf = "1.4"

[features]
default = []
blas = ["ndarray/blas", "blas-sys"]
openblas = ["blas", "blas-sys/openblas"]
accelerate = ["blas", "blas-sys/accelerate"]

[build-dependencies]
protoc-rust   = "1.4"
tempdir = "0.3"

[dev-dependencies]
bencher = "0.1"
flate2 = "0.2"
itertools = "0.6"
reqwest = "0.7"
tar = "0.4"
tensorflow = "0.5"
proptest = "0.2"

[[bench]]
harness = false
name = "conv"

[[bench]]
harness = false
name = "inceptionv3"
