[package]
name = "tfdeploy"
version = "0.0.1"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
protobuf = "*"
ndarray = "*"
num-traits = "*"
error-chain = "*"
maplit="*"
tensorflow = "*"
downcast-rs = "*"
bencher = "*"

[build-dependencies]
protoc-rust   = "*"
tempdir = "0.3"

[dev-dependencies]

[[bench]]
name = "hotword"
harness = false
