[package]
name = "tfdeploy"
version = "0.0.2"
license = "MIT/Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow inference"
repository = "https://github.com/kali/tensorflow-deploy-rust"
keywords = [ "TensorFlow", "NeuralNetworks" ]
build="build.rs"
categories = [ "science" ]

[badges]
travis-ci = { repository = "kali/tensorflow-deploy-rust" }

[dependencies]
protobuf = "1.4"
ndarray = "0.10"
num-traits = "0.1"
error-chain = "0.10"
maplit="0.1"
downcast-rs = "1.0"

[build-dependencies]
protoc-rust   = "1.4"
tempdir = "0.3"

[dev-dependencies]
bencher = "0.1"

[[bench]]
harness= false
name = "conv"
