[package]
name = "tfdeploy"
version = "0.0.1"
license = "MIT/Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow inference"
repository = "https://github.com/kali/tensorflow-deploy-rust"
keywords = [ "TensorFlow", "Neural Networks" ]
build="build.rs"
categories = [ "Science" ]

[dependencies]
protobuf = "*"
ndarray = "*"
num-traits = "*"
error-chain = "*"
maplit="*"
downcast-rs = "*"

[build-dependencies]
protoc-rust   = "*"
tempdir = "0.3"

[dev-dependencies]
