[workspace]
members = [
    "linalg",
    "core",
    "tensorflow",
    "tensorflow/inceptionv3",
    "tensorflow/deepspeech",
    "onnx",
    "cli"
]

[profile.release]
lto = true

[profile.bench]
debug = true
