[package]
name = "tfdeploy"
version = "0.0.1"
license = "MIT/Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow inference"
repository = "https://github.com/kali/tensorflow-deploy-rust"
keywords = [ "TensorFlow", "NeuralNetworks" ]
build="build.rs"
categories = [ "science" ]

[badges]
travis-ci = { repository = "kali/tensorflow-deploy-rust" }

[dependencies]
downcast-rs = "1.0"
error-chain = "0.10"
image = "0.15"
log = "0.3"
maplit="0.1"
ndarray = "0.10"
num-traits = "0.1"
petgraph = "0.4"
protobuf = "1.4"

[build-dependencies]
protoc-rust   = "1.4"
tempdir = "0.3"

[dev-dependencies]
bencher = "*"

[[bench]]
harness= false
name = "conv"
