[package]
name = "tfdeploy"
version = "0.0.3-pre"
license = "MIT/Apache-2.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
description = "Tiny, no-nonsense, self contained, TensorFlow inference"
repository = "https://github.com/kali/tensorflow-deploy-rust"
keywords = [ "TensorFlow", "NeuralNetworks" ]
build="build.rs"
categories = [ "science" ]

[badges]
travis-ci = { repository = "kali/tensorflow-deploy-rust" }

[dependencies]
downcast-rs = "1.0"
error-chain =  { version = "0.10", default-features=false }
image = "0.15"
log = "0.3"
maplit="0.1"
ndarray = { version = "0.10", features = [ "blas" ] }
blas-sys = { version = "0.6", features = [ "openblas" ], default-features=false }
#blas-sys = { version = "0.6", features = [ "accelerate" ], default-features=false }
num-traits = "0.1"
protobuf = "1.4"
tensorflow = { version = "*", optional = true }

[build-dependencies]
protoc-rust   = "1.4"
tempdir = "0.3"

[dev-dependencies]
bencher = "0.1"
flate2 = "*"
image = "*"
itertools = "*"
reqwest = "*"
tar = "*"
tensorflow = "*"
proptest = "*"

[[bench]]
harness = false
name = "conv"

[[bench]]
harness = false
name = "inceptionv3"
