[package]
name = "conform"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
flate2 = "*"
image = "*"
itertools = "*"
ndarray = "*"
protobuf = "*"
reqwest = "*"
tar = "*"
tensorflow = "*"
tfdeploy = { path = "..", features = [ "tensorflow" ] }
