[package]
name = "conform"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]

[dependencies]
error-chain = "*"
flate2 = "*"
jpeg-decoder = "*"
ndarray = "*"
reqwest = "*"
tar = "*"
tensorflow = "*"
tfdeploy = { path = ".."}
