[package]
name = "cli"
version = "1.0.0"
authors = ["Romain Liautaud <romain.liautaud@snips.ai>"]
autobenches = false

[dependencies]
box_drawing = "0.1"
clap = "2.31"
colored = "1.6"
conform = { path = "../tensorflow/conform" }
error-chain = "0.12"
insideout = "0.1.0"
lazy_static = "1.0"
log = "0.4"
ndarray = "0.12"
prettytable-rs = { git = "https://github.com/liautaud/prettytable-rs" }
rand = "0.5"
pretty_env_logger = "0.2"
terminal_size = "0.1.7"
textwrap = "0.10"
tract = { path = "../core", features=["serialize"] }
tract-tensorflow = { path = "../tensorflow" }
tract-onnx = { path = "../onnx" }
pbr = "1.0"
atty = "0.2"
itertools = "0.7"
libc = "0.2"
open = "1.2"

[features]
default = []
tensorflow = []

[dev-dependencies]
criterion = "0.2"

# [[bench]]
# name = "streaming_conv2d"
# harness = false

# [[bench]]
# name = "streaming_diamond"
# harness = false
